{{- $mongoConnectionString := printf "mongodb://%s:%s@%s:%s?authSource=%s" .Values.mongodb.auth.username .Values.mongodb.auth.password .Values.mongodb.fullnameOverride ( .Values.mongodb.service.port | toString ) .Values.mongodb.auth.database -}}
{{- $minioEndpoint := printf "%s:%s" .Values.minio.fullnameOverride ( .Values.minio.service.port | toString ) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dpio-asset-api.fullname" . }}-secrets
  labels:
    {{- include "dpio-asset-api.labels" . | nindent 4 }}
type: Opaque
data:
  AssetsDatabaseSettingsConnectionString: {{ $mongoConnectionString | b64enc | quote }}
  AssetsDatabaseSettingsDatabaseName: {{ .Values.mongodb.auth.database | b64enc | quote }}
  AssetsDatabaseSettingsCollectionName: {{ .Values.databaseCollectionName | b64enc | quote }}
  StorageSettingsEndpointUrl: {{ $minioEndpoint | b64enc | quote }}
  StorageSettingsBucketName: {{ .Values.storageBucketName | b64enc | quote }}
  StorageSettingsAccessKey: {{ .Values.minio.accessKey.password | b64enc | quote }}
  StorageSettingsSecretKey: {{ .Values.minio.secretKey.password | b64enc | quote }}
  StorageSettingsEnableHTTPS: {{ .Values.useMinioHTTPS | b64enc | quote }}
